import { deleteRecord, saveRecord } from '@/app/admin/(protected)/actions'

type Field = { key: string; label: string; type?: 'textarea' | 'number' | 'url' }
type Row = Record<string, unknown>

export function CrudPage({ title, description, table, fields, rows, returnTo }: { title: string; description: string; table: 'rooms' | 'amenities' | 'faqs' | 'gallery_images'; fields: Field[]; rows: Row[]; returnTo: string }) {
  return <div className="space-y-8"><header><p className="text-sm text-muted-foreground">Property</p><h1 className="mt-1 text-3xl font-semibold">{title}</h1><p className="mt-2 text-muted-foreground">{description}</p></header><section className="rounded-2xl border border-border bg-background p-5"><h2 className="font-semibold">Add {title.slice(0, -1)}</h2><Editor table={table} fields={fields} returnTo={returnTo} /></section><section className="space-y-3">{rows.length === 0 ? <div className="rounded-2xl border border-dashed border-border bg-background p-10 text-center text-muted-foreground">No {title.toLowerCase()} added yet.</div> : rows.map((row) => <details key={String(row.id)} className="rounded-2xl border border-border bg-background p-5"><summary className="cursor-pointer font-medium">{String(row.name ?? row.question ?? row.alt_text ?? row.storage_path)} <span className="ml-2 text-xs text-muted-foreground">{row.is_visible === false ? 'Hidden' : 'Visible'}</span></summary><Editor table={table} fields={fields} returnTo={returnTo} row={row} /><form action={deleteRecord} className="mt-3"><input type="hidden" name="table" value={table}/><input type="hidden" name="id" value={String(row.id)}/><input type="hidden" name="returnTo" value={returnTo}/><button className="text-sm text-red-600" type="submit">Delete</button></form></details>)}</section></div>
}

function Editor({ table, fields, returnTo, row }: { table: string; fields: Field[]; returnTo: string; row?: Row }) {
  return <form action={saveRecord} className="mt-4 grid gap-4 sm:grid-cols-2"><input type="hidden" name="table" value={table}/><input type="hidden" name="id" value={String(row?.id ?? '')}/><input type="hidden" name="returnTo" value={returnTo}/>{fields.map((field) => <label key={field.key} className={field.type === 'textarea' ? 'sm:col-span-2' : ''}><span className="text-sm font-medium">{field.label}</span>{field.type === 'textarea' ? <textarea name={field.key} defaultValue={String(row?.[field.key] ?? '')} className="mt-1 min-h-24 w-full rounded-xl border border-border bg-background p-3"/> : <input name={field.key} type={field.type ?? 'text'} defaultValue={String(row?.[field.key] ?? '')} className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2"/>}</label>)}<label className="flex items-center gap-2 text-sm"><input name="is_visible" type="checkbox" defaultChecked={row ? Boolean(row.is_visible) : true}/> Visible</label><label><span className="text-sm font-medium">Sort order</span><input name="sort_order" type="number" min="0" defaultValue={String(row?.sort_order ?? 0)} className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2"/></label><button type="submit" className="rounded-xl bg-primary px-4 py-2 font-medium text-primary-foreground sm:col-span-2">Save</button></form>
}
